name: build

on:
  push:
    paths:
      - ".github/**"
      - "src/**"
      - "cli/extern/**"
      - "cli/cli.cpp"
      - "cli/CMakeLists.txt"
      - "cmake/**"
      - "include/**"
      - "tests/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"

permissions:
  contents: read

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2025-vs2026
            configure_preset: msvc-x86
            test_preset: msvc-x86-test
            build_preset: msvc-x86-build
          - os: ubuntu-24.04-arm
            configure_preset: unix
            test_preset: unix-test
            build_preset: unix-build
          - os: ubuntu-24.04
            configure_preset: unix
            test_preset: unix-test
            build_preset: unix-build
          - os: macos-26
            configure_preset: unix
            test_preset: unix-test
            build_preset: unix-build

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Configure, build and test
        uses: lukka/run-cmake@v10
        with:
          configurePreset: ${{ matrix.configure_preset }}
          buildPreset: ${{ matrix.build_preset }}
          testPreset: ${{ matrix.test_preset }}
          testPresetAdditionalArgs: "['--output-on-failure']"
