name: build examples

on:
  push:
    paths:
      - ".github/**"
      - "tools/cmake/**"
      - "examples/**"
      - "include/**"
      - "src/**"
      - "extern/**"
      - "CMakeLists.txt"
      - "CMakePresets.json"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2022
            configure_preset: msvc-x86
            build_preset: msvc-x86-build
            output_txt211json: examples/build_msvc/txt211json/Release
            output_utx121webp: examples/build_msvc/utx121webp/Release
            executable_txt211json: txt211json.exe
            executable_utx121webp: utx121webp.exe
            zip_name_utx121webp: utx121webp_windows.zip
            zip_name_txt211json: txt211json_windows.zip
          - os: ubuntu-22.04
            configure_preset: unix
            build_preset: unix-build
            cc: gcc-12
            cxx: g++-12
            output_utx121webp: examples/build_unix/utx121webp
            output_txt211json: examples/build_unix/txt211json
            executable_utx121webp: utx121webp
            executable_txt211json: txt211json
            zip_name_utx121webp: utx121webp_linux.zip
            zip_name_txt211json: txt211json_linux.zip
          - os: macos-14
            configure_preset: unix
            build_preset: unix-build
            output_utx121webp: examples/build_unix/utx121webp
            output_txt211json: examples/build_unix/txt211json
            executable_utx121webp: utx121webp
            executable_txt211json: txt211json
            zip_name_utx121webp: utx121webp_macos.zip
            zip_name_txt211json: txt211json_macos.zip
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build
        uses: lukka/run-cmake@v10
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        with:
          configurePreset: ${{ matrix.configure_preset }}
          buildPreset: ${{ matrix.build_preset }}
          cmakeListsTxtPath: examples/CMakeLists.txt

      - name: Zip utx121webp
        uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          type: "zip"
          filename: ${{ matrix.zip_name_utx121webp }}
          directory: ${{ matrix.output_utx121webp }}
          path: ${{ matrix.executable_utx121webp }}

      - name: Zip txt211json
        uses: thedoctor0/zip-release@0.7.5
        if: startsWith(github.ref, 'refs/tags/')
        with:
          type: "zip"
          filename: ${{ matrix.zip_name_txt211json }}
          directory: ${{ matrix.output_txt211json }}
          path: ${{ matrix.executable_txt211json }}

      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ${{ matrix.output_utx121webp }}/${{ matrix.zip_name_utx121webp }}
            ${{ matrix.output_txt211json }}/${{ matrix.zip_name_txt211json }}
