name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-2025-vs2026
            configure_preset: msvc-x86
            build_preset: msvc-x86-build
            output_name: l2encdec_windows
          - os: ubuntu-24.04
            configure_preset: unix
            build_preset: unix-build
            cc: gcc-13
            cxx: g++-13
            output_name: l2encdec_linux
          - os: macos-15
            configure_preset: unix
            build_preset: unix-build
            output_name: l2encdec_mac
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Abort if tag is not on main
        shell: bash
        run: |
          git fetch origin main --depth=1
          TAG_SHA=$(git rev-parse ${{ github.sha }})
          MAIN_SHA=$(git rev-parse origin/main)

          if ! git merge-base --is-ancestor "$TAG_SHA" "$MAIN_SHA"; then
            exit 1
          fi

      - name: Setup CMake
        uses: lukka/get-cmake@latest

      - name: Build
        uses: lukka/run-cmake@v10
        env:
          CC: ${{ matrix.cc }}
          CXX: ${{ matrix.cxx }}
        with:
          configurePreset: ${{ matrix.configure_preset }}
          buildPreset: ${{ matrix.build_preset }}
          configurePresetAdditionalArgs: >
            -DL2ENCDEC_OUTPUT_NAME=${{ matrix.output_name }}

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: |
            build_*/*.zip
